In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
prices = np.array([25,20,15,25,18])

In [4]:
prices

array([25, 20, 15, 25, 18])

In [5]:
#prices DF 
prices_reshaped = prices.reshape(1,5)
prices_df = pd.DataFrame(prices_reshaped,
                         index=['Priser'],
                        columns=['Räkmacka','Kyckling','Vegan','Tonfisk','Ägg'])
prices_df

Räkmacka  Kyckling  Vegan  Tonfisk  Ägg
Priser        25        20     15       25   18

In [6]:
np.random.seed(1)
weekly_sales = np.random.randint(20,25,size=(7,5))
weekly_sales

array([[23, 24, 20, 21, 23],
       [20, 20, 21, 24, 24],
       [21, 22, 24, 22, 24],
       [23, 24, 22, 24, 22],
       [24, 21, 21, 20, 21],
       [21, 21, 21, 20, 24],
       [21, 20, 20, 23, 22]])

In [7]:
weekly_sales_df = pd.DataFrame(weekly_sales,
                               index=['Mån','Tis','Ons','Tors','Fre','Lör','Sön'],
                               columns=['Räkmacka','Kyckling','Vegan','Tonfisk','Ägg'])
weekly_sales_df

Räkmacka  Kyckling  Vegan  Tonfisk  Ägg
Mån         23        24     20       21   23
Tis         20        20     21       24   24
Ons         21        22     24       22   24
Tors        23        24     22       24   22
Fre         24        21     21       20   21
Lör         21        21     21       20   24
Sön         21        20     20       23   22

In [8]:
total_sales = prices.dot(weekly_sales.T)
total_sales

array([2294, 2247, 2307, 2381, 2213, 2192, 2196])

In [9]:
total_sales_df = prices_df.dot(weekly_sales_df.T)
total_sales_df

Mån   Tis   Ons  Tors   Fre   Lör   Sön
Priser  2294  2247  2307  2381  2213  2192  2196

In [10]:
final_sales = weekly_sales_df.copy()
final_sales['Total (SEK)'] = total_sales_df.T

In [11]:
final_sales

Räkmacka  Kyckling  Vegan  Tonfisk  Ägg  Total (SEK)
Mån         23        24     20       21   23         2294
Tis         20        20     21       24   24         2247
Ons         21        22     24       22   24         2307
Tors        23        24     22       24   22         2381
Fre         24        21     21       20   21         2213
Lör         21        21     21       20   24         2192
Sön         21        20     20       23   22         2196

In [12]:
np.mean(total_sales).astype(int)

2261

In [13]:
np.var(total_sales).astype(int)

4155

In [14]:
np.std(total_sales,ddof=1).astype(int)

69

In [15]:
price_calc = np.array([np.mean(total_sales).astype(int),np.var(total_sales).astype(int),np.std(total_sales,ddof=1).astype(int)])
price_calc

array([2261, 4155,   69])

In [16]:
price_calc_df = pd.DataFrame(price_calc.reshape(1,3),
                      index=['Redovisning'],
                      columns=['Medelvärde','Varians','Sandardavvikelse'])
price_calc_df

Medelvärde  Varians  Sandardavvikelse
Redovisning        2261     4155                69

In [17]:
final_sales

Räkmacka  Kyckling  Vegan  Tonfisk  Ägg  Total (SEK)
Mån         23        24     20       21   23         2294
Tis         20        20     21       24   24         2247
Ons         21        22     24       22   24         2307
Tors        23        24     22       24   22         2381
Fre         24        21     21       20   21         2213
Lör         21        21     21       20   24         2192
Sön         21        20     20       23   22         2196

In [18]:
price_calc_df

Medelvärde  Varians  Sandardavvikelse
Redovisning        2261     4155                69

In [19]:
weekly_sales_df

Räkmacka  Kyckling  Vegan  Tonfisk  Ägg
Mån         23        24     20       21   23
Tis         20        20     21       24   24
Ons         21        22     24       22   24
Tors        23        24     22       24   22
Fre         24        21     21       20   21
Lör         21        21     21       20   24
Sön         21        20     20       23   22

In [20]:
np.mean(weekly_sales_df).astype(int)

21

In [25]:
pd.DataFrame(np.var(weekly_sales_df,1).astype(int))

0
Mån   2
Tis   3
Ons   1
Tors  0
Fre   1
Lör   1
Sön   1

In [26]:
pd.DataFrame(np.std(weekly_sales_df,1).astype(int))

0
Mån   1
Tis   1
Ons   1
Tors  0
Fre   1
Lör   1
Sön   1